ktor:
    application:
        modules:
            - com.nalldev.ApplicationKt.module
    deployment:
        port: 8080
    development: true

jwt:
    secret: "secret"
    issuer: "http://localhost:3306/"
    audience: "http://localhost:3306/test"
    realm: "You are not authenticated"
